version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: odoo-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: odoo
      POSTGRES_DB: odoo
    volumes:
      - odoo_db_data:/var/lib/postgresql/data
    networks:
      - odoo_network

  odoo:
    image: odoo:latest
    container_name: odoo-container
    depends_on:
      - db
    ports:
      - "8070:8069"
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=odoo
      - DB_PASSWORD=odoo
    command: ["odoo", "-d", "odoo", "-i", "base"]
    volumes:
      - odoo_data:/var/lib/odoo
    networks:
      - odoo_network

volumes:
  odoo_db_data:
  odoo_data:

networks:
  odoo_network:
    driver: bridge